version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: db_todolist
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db_todolist
    volumes:
      - pg_todolist:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pg_todolist: